[tool.poetry]
name = "amazon-cryptography-internal-dafny-shim-ddb"
version = "0.1.0"
description = ""
authors = ["AWS Crypto Tools <aws-crypto-tools@amazon.com>"]
packages = [
    { include = "com_amazonaws_dynamodb", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.11.0"
boto3 = "^1.28.38"
# TODO: Depend on PyPi once Smithy-Python publishes their Python package there
smithy-python = { path = "../../../smithy-dafny/codegen/smithy-dafny-codegen-modules/smithy-python/python-packages/smithy-python", develop = false}
DafnyRuntimePython = "~4.7.0"
standard-library = { path = "../../../StandardLibrary/runtimes/python", develop = false}

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
